### ISSUE TITLE
Size of the Font

### ISSUE THREAD

**Issue by antoineder** [aproxima/htmlq#14]
Hello, 

Everything is working well with HTMLQ except the size of the font during step 1. The size of the statements are too big for the boxes, the participants can't read all the statements properly. So I tried with this =

    <item id="smallFont">false</item>
But It doesn't change anything. 
So does someone know how to reduce the size of these statements? It would be really really helpful for my survey...

**Comment by sowrahmane** [comment]
Hello, 

Try to modify the size of the statements by changing (adding "font-size" option) in htmlq.css (which can locate in the stylesheets folder).
I think this is the part of the code you have to change by adding "font-size" style: 

/* step1 */
/* hide all except the first statement */
#step1 {
    padding-top: 50px;
}

**Comment by antoineder** [comment]
Thank you very much for the quick answer, you've solved my problem! 

Have a nice day
